name: CI
on: [push, pull_request]
env:
  FOREMAN_PLUGIN_NAME: foreman_vault
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        foreman-core-branch: [2.0-stable, develop, migrations_issue]
        ruby-version: [2.5]
        node-version: [10]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: kamils-iRonin/foreman
          ref: ${{ matrix.foreman-core-branch }}
      - uses: actions/checkout@v2
        with:
          path: ${{ env.FOREMAN_PLUGIN_NAME }}
      - run: mv config/database.yml.example ../config/database.yml
        working-directory: ${{ env.FOREMAN_PLUGIN_NAME }}
      - run: cat config/database.yml
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version:  ${{ matrix.node-version }}
      - name: Setup Foreman Plugin
        uses: kamils-iRonin/setup-foreman-plugin@migrations_issue
        with:
          plugin-name: ${{ env.FOREMAN_PLUGIN_NAME }}
      - run: cat db/schema.rb
      - name: Run plugin tests
        run: bundle exec rake test:${FOREMAN_PLUGIN_NAME}
